data:
    name: 'colon'
    image_path: '/home/student/ColonSuperPoint/ColonExperiments/datasets/endomapper_train/33/images'
    validation_size: 0
    cache_in_memory: false
    preprocessing:
        use_colonoscopy_preprocessing: true
        half_resolution: false
        camera_mask_path: '/home/student/ColonSuperPoint/ColonExperiments/datasets/endomapper_train/33/camera_mask.png'
model: 
    name: 'super_point'
    batch_size: 5
    learning_rate: 0.001
    detection_threshold: 0.015  # 0.001
    nms: 4
    # top_k: 600
    homography_adaptation:
        num: 100
        aggregation: 'sum'
        filter_counts: 0
        valid_border_margin: 3
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.85
eval_iter: -1
